config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'chat_rooms/index'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  resources :products do
    scope module: :products do
      resources :purchases, only: [:new] do
        get :success, on: :collection
      end
      resources :payments do
        get :success, on: :collection
        get :cancel, on: :collection
      end
      resources :stripe_checkouts, only: [:create]
    end
  end

  resources :categories
  resources :races
  resources :farmers
  resources :chat_rooms do
    resources :messages
  end

  devise_for :users
  get 'welcomes/index'

  # For turbochat
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  get 'user/:id', to: 'users#show', as: 'user'

  ####

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcomes#index"

  get "vendeur", to: "welcomes#vendeur"
  get "client", to: "welcomes#client"
  get "list", to: "welcomes#list"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :cart_products
  has_many :products, through: :cart_products

  def total
    cart_products.to_a.sum { |cart_product| cart_product.total }
  end

end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :product
  belongs_to :cart

  def total
    product.current_price * rate
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord

  has_many :messages
  has_many :participants, dependent: :destroy

  validates_uniqueness_of :name
  scope :public_chat_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to "chat_rooms" unless self.is_private
  end

  def self.create_private_chat_room(users, chat_room_name)
    single_chat_room = ChatRoom.create(name: chat_room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, chat_room_id: single_chat_room.id)
    end
    single_chat_room
  end
  validates_uniqueness_of :name
  scope :public_chat_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_append_to "chat_rooms" }

end

app/models/farmer.rb
class Farmer < ApplicationRecord

  belongs_to :user

  validates :name, presence: true
  validates :adress, presence: true
  validates :description, presence: true

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :chat_room

  before_create :confirm_participant

  def confirm_participant
    return unless chat_room.is_private

    is_participant = Participant.where(user_id: self.user.id, chat_room_id: self.chat_room.id).first
    throw :abort unless is_participant
  end

end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/product.rb
class Product < ApplicationRecord

  has_many_attached :pictures

  has_many :cart_products
  has_many :carts, through: :cart_products
  belongs_to :race
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :current_price, presence: true
  validates :disponibility, presence: true
  validates :evaluation, presence: true
  validates :race_id, presence: false
  validates :category_id, presence: true

end

app/models/race.rb
class Race < ApplicationRecord

  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord

  # Active_record association

  has_one_attached :photo

  has_one :farmer
  has_many :messages

  ###

  # Validate custom parameters (or fields) for user
  validates :role, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :country, presence: true
  validates :city, presence: true
  validates :phone, presence: true
  validates :address, presence: true

  ###

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    rate = params[:rate].to_i
    current_cart_product = @cart.cart_products.find_by(product_id: @product.id)
    if current_cart_product && rate > 0
      current_cart_product.update(rate:)
    elsif rate <= 0
      current_cart_product.destroy
    else
      @cart.cart_products.create(product: @product, rate:)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                    partial: 'cart/cart',
                                                    locals: { cart: @cart }),
                              turbo_stream.replace(@product)]
      end
    end

  end

  def remove
    CartProduct.find_by(id: params[:id]).destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart})
      end
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @chat_room = ChatRoom.new
    @chat_rooms = ChatRoom.public_chat_rooms
    @chat_room_name = get_name(@user, current_user)
    @single_chat_room = ChatRoom.where(name: @chat_room_name).first || ChatRoom.create_private_chat_room([@user, current_user], @chat_room_name)

    @message = Message.new
    @messages = @single_chat_room.messages.order(created_at: :asc)
    render 'chat_rooms/index'
  end

  private

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/users/_user.html.erb
<div>
    <%= link_to user.first_name, user, data: { turbo: "false" } %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>