config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'chat_rooms/index'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  resources :products do
    scope module: :products do
      resources :purchases, only: [:new] do
        get :success, on: :collection
      end
      resources :payments do
        get :success, on: :collection
        get :cancel, on: :collection
      end
      resources :stripe_checkouts, only: [:create]
    end
  end

  resources :categories
  resources :races
  resources :farmers
  resources :chat_rooms do
    resources :messages
  end

  devise_for :users
  get 'welcomes/index'

  # For turbochat
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  get 'user/:id', to: 'users#show', as: 'user'

  ####

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcomes#index"

  get "vendeur", to: "welcomes#vendeur"
  get "client", to: "welcomes#client"
  get "list", to: "welcomes#list"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :cart_products
  has_many :products, through: :cart_products

  def total
    cart_products.to_a.sum { |cart_product| cart_product.total }
  end

end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :product
  belongs_to :cart

  def total
    product.current_price * rate
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord

  has_many :messages
  has_many :participants, dependent: :destroy

  validates_uniqueness_of :name
  scope :public_chat_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to "chat_rooms" unless self.is_private
  end

  def self.create_private_chat_room(users, chat_room_name)
    single_chat_room = ChatRoom.create(name: chat_room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, chat_room_id: single_chat_room.id)
    end
    single_chat_room
  end
  validates_uniqueness_of :name
  scope :public_chat_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_append_to "chat_rooms" }

end

app/models/farmer.rb
class Farmer < ApplicationRecord

  belongs_to :user

  validates :name, presence: true
  validates :adress, presence: true
  validates :description, presence: true

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :chat_room

  before_create :confirm_participant

  def confirm_participant
    return unless chat_room.is_private

    is_participant = Participant.where(user_id: self.user.id, chat_room_id: self.chat_room.id).first
    throw :abort unless is_participant
  end

end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/product.rb
class Product < ApplicationRecord

  has_many_attached :pictures

  has_many :cart_products
  has_many :carts, through: :cart_products
  belongs_to :race
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :current_price, presence: true
  validates :disponibility, presence: true
  validates :evaluation, presence: true
  validates :race_id, presence: false
  validates :category_id, presence: true

end

app/models/race.rb
class Race < ApplicationRecord

  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord

  # Active_record association

  has_one_attached :photo

  has_one :farmer
  has_many :messages

  ###

  # Validate custom parameters (or fields) for user
  validates :role, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :country, presence: true
  validates :city, presence: true
  validates :phone, presence: true
  validates :address, presence: true

  ###

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  before_action :authenticate_user!, only: %i[ vendeur client list ]

  def index

    @users = User.all

  end

  def vendeur

    @users = User.all

    if current_user && current_user.role == "Eleveur"
      @farmers = current_user.farmer
    else
      render :back
    end

  end

  def client

    @users = User.all

  end

  def list
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_navbar.html.erb
<nav class="navbar" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <%= link_to "Chicken app", root_path, class:"navbar-brand" %>
    <%= link_to "Page d'accueil", root_path, class:"navbar-brand" %>
    <%= link_to "A propos", root_path, class:"navbar-brand" %>
    <% if current_user %>
        <%= button_to("Deconnexion", destroy_user_session_path, type: "button", method: :delete, class:"btn btn-sm btn-outline-secondary") %>
        <%= current_user.last_name %>
    <% else %>
        <%= link_to "Connexion", new_user_session_path, class:"btn btn-sm btn-outline-secondary" %>
        <%= link_to "Inscription", new_user_registration_path, class:"btn btn-sm btn-outline-secondary" %>
    <% end %>
    <form class="d-flex input-group" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-sm btn-outline-success" type="submit">Recherche</button>
    </form>
  </div>
</nav>

app/views/welcomes/client.html.erb
<%= render partial: 'cart/cart' if @render_cart %>

app/views/welcomes/index.html.erb
<% if current_user %>
    <%= link_to "Lancer une conversation", chat_rooms_path %>
<% end %>

app/views/welcomes/list.html.erb
<% @users.each do |user| %>
    <% if user.role == "Client" %>
        <%= user.last_name %>
        <%= user.first_name %>
    <% end %>
<% end %>

app/views/welcomes/vendeur.html.erb
<div>
    <p><b>Magasin </b><%= current_user.farmer.name %></p>
    <p><b>Adresse : </b><%= current_user.farmer.adress %></p>
    <p><b>Details : </b><%= current_user.farmer.description %></p>
</div>

<p><%= link_to "Edit this farmer", edit_farmer_path(@farmers) %></p>
<p><%= button_to "Destroy this farmer", @farmer, method: :delete %></p>