config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'chat_rooms/index'

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'

  resources :products do
    scope module: :products do
      resources :purchases, only: [:new] do
        get :success, on: :collection
      end
      resources :payments do
        get :success, on: :collection
        get :cancel, on: :collection
      end
      resources :stripe_checkouts, only: [:create]
    end
  end

  resources :categories
  resources :races
  resources :farmers
  resources :chat_rooms do
    resources :messages
  end

  devise_for :users
  get 'welcomes/index'

  # For turbochat
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  get 'user/:id', to: 'users#show', as: 'user'

  ####

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcomes#index"

  get "vendeur", to: "welcomes#vendeur"
  get "client", to: "welcomes#client"
  get "list", to: "welcomes#list"

end

app/models/product.rb
class Product < ApplicationRecord

  has_many_attached :pictures

  has_many :cart_products
  has_many :carts, through: :cart_products
  belongs_to :race
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :current_price, presence: true
  validates :disponibility, presence: true
  validates :evaluation, presence: true
  validates :race_id, presence: false
  validates :category_id, presence: true

end

app/controllers/products/payments_controller.rb
module Products
  class PaymentsController < ApplicationController

    before_action :set_product

    def new

    end

    def create
      customer = Stripe::Customer.create(
        name: current_user.first_name,
        email: current_user.email,
      )

      session = Stripe::Checkout::Session.create(
        customer: customer,
        payment_method_types: ['card'],
        line_items: [{
          quantity: 1,
          price_data: {
            currency: 'usd',
            product_data: {
              name: @product.name,
            },
            unit_amount: (@product.current_price * 100).to_i,
          }
        }],
        mode: 'payment',
        success_url: root_url,
        cancel_url: root_url
      )

      redirect_to root_url
    end

    def success
      redirect_to root_url, notice: "Purchase Successful"
    end

    def cancel
      redirect_to root_url, notice: "Purchase Unsuccessful"
    end

    private

    def set_product
      @product = Product.find(params[:product_id])
    end

  end

end

app/controllers/products/purchases_controller.rb
module Products
  class PurchasesController < ApplicationController

    before_action :set_product

    def new

    end

    def success

    end

    private

    def set_product
      @product = Product.find(params[:product_id])
    end

  end
end

app/controllers/products/stripe_checkouts_controller.rb
module Products
  class StripeCheckoutsController < ApplicationController

    def create
      @product = Product.find(params[:product_id])

      session = Stripe::Checkout::Session.create(
        ui_mode: 'embedded',
        payment_method_types: ['card'],
        line_items: [{
          quantity: 1,
          price_data: {
            currency: 'usd',
            product_data: {
              name: @product.name,
            },
            unit_amount: (@product.current_price * 100).to_i,
          },
        }],
        mode: 'payment',
        return_url: success_product_purchases_url(@product),
      )

      render json: { clientSecret: session.client_secret }
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :current_price, :disponibility, :evaluation, :race_id, :category_id, pictures: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :current_price, style: "display: block" %>
    <%= form.text_field :current_price %>
  </div>

  <div>
    <%= form.label :disponibility, style: "display: block" %>
    <%= form.text_field :disponibility %>
  </div>

  <div>
    <%= form.label :evaluation, style: "display: block" %>
    <%= form.text_area :evaluation %>
  </div>

  <div>
    <%= form.label :pictures, "Joindre des photos", style: "display: block" %>
    <%= form.file_field :pictures, multiple:true %>
  </div><br/>

  <div>
    <%= form.label :race_id, style: "display: block" %>
    <%= form.text_field :race_id %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">

  <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
    <div>
      <% product.pictures.each do |picture| %>
        <%= image_tag(picture, style: "object-fit: contain; width:50px; height:50px;") %><strong> </strong>
      <% end %><br/>
      <i><%= product.name %></i>
    </div>

    <div>
      <strong>Description</strong><br/>
      <%= product.description %>
    </div><pre> </pre>

    <div>
      <strong>Prix courant</strong><br/>
      <%= product.current_price %>
    </div><pre> </pre>

    <div>
      <strong>Disponibility</strong><br/>
      <%= product.disponibility %>
    </div><pre> </pre>

    <div>
      <strong>Evaluation</strong><br/>
      <%= product.evaluation %>
    </div><pre> </pre>

    <div>
      <%= form_with(url: cart_add_path) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <%= f.number_field :rate, value: 0, min: 1 %><br/>
        <%= f.submit "Ajouter au panier" %>
      <% end %>
    </div>

  </div>

</div><br/>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: 'cart/cart' %>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <% if current_user && current_user.role == "Eleveur" %>
    <%= link_to "Edit this product", edit_product_path(@product) %>
    <%= link_to "Back to products", products_path %>
    <%= button_to "Destroy this product", @product, method: :delete %>
  <% else %>
    <%= link_to "Back to products", products_path %>
  <% end %>
</div>

<% if current_user %>
  <div class="my-4 py-2">
    <%= link_to "Acheter", new_product_payment_path(@product), class:"btn btn-success" %>
  </div>
<% else %>

<% end %>